##
# DO NOT EDIT THIS FILE.
# This locale file is auto-generated from the Wordchuck API by the Wordchuck Ruby gem. Any manual
# updates to an rb file will be lost when this file is regenerated. This current file will be only
# versioned once, or discarded.
#   http://wordchuck.com
##

{
  :'en' =>

{
  :nav => {
    :blog => "Blog",
    :photos => "Photos",
    :bio => "Bio",
    :cv => "CV",
    :readings => "Readings"
  },
  :bio_page => {
    :paragraph_1 => "Andy Brett was born on September 26th in an undisclosed location in northeast Ohio. Educated first by his parents, and then by nuns, and finally by the Socratic method, he left Ohio at the age of 17 with a tendency to ask impertinent questions, as well as \"real-world\" experience as a <a href=\"http://www.kirtlandcc.org/\">caddy</a>, tutor, landscaper, camp counselor, and Panera sandwich maker. Luckily, he wasn't headed for the real world but rather the orange bubble of Princeton University. ",
    :paragraph_2 => "After four years, Andy emerged with a degree and a few more hats, including Long Trail Patrolman, storm chaser, and human health risk analyst. He also took many courses, and while his degree is technically in Civil and Environmental Engineering and Computer Science, the bulk of the credit for his higher education belongs to the professors from these four courses: "
  }
}

}

