##
# DO NOT EDIT THIS FILE.
# This locale file is auto-generated from the Wordchuck API by the Wordchuck Ruby gem. Any manual
# updates to an rb file will be lost when this file is regenerated. This current file will be only
# versioned once, or discarded.
#   http://wordchuck.com
##

{
  :'es' =>

{
  :nav => {
    :blog => "Blog",
    :photos => "Fotos",
    :bio => "Bio",
    :cv => "CV",
    :readings => "Lecturas"
  },
  :bio_page => {
    :paragraph_1 => "Andy Brett nació el 26 de mayo en un lugar no revelado en el noreste de Ohio de septiembre. Educado primero por sus padres, y luego por las monjas, y, finalmente, por el método socrático, que dejó de Ohio a la edad de 17 años con una tendencia a hacer preguntas impertinentes, así como del \"mundo real\" la experiencia como un <a href=\"http://www.kirtlandcc.org/\">carrito de compra</a> , tutor, paisajista , campo de consejero, y el fabricante de Panera sándwich. Por suerte, no se dirigía hacia el mundo real, sino más bien la burbuja de color naranja de la Universidad de Princeton.",
    :paragraph_2 => "Después de cuatro años, Andy surgido con un grado y unos cuantos sombreros más, incluyendo Long Trail patrullero, cazador de tormentas, y analista de riesgos para la salud humana. También tomó cursos de muchos, y aunque su título es técnico en Ingeniería Civil y Ambiental y Ciencias de la Computación, la mayor parte del mérito de sus estudios superiores pertenecen a los profesores de estos cuatro cursos:"
  }
}

}

