##
# DO NOT EDIT THIS FILE.
# This locale file is auto-generated from the Wordchuck API by the Wordchuck Ruby gem. Any manual
# updates to an rb file will be lost when this file is regenerated. This current file will be only
# versioned once, or discarded.
#   http://wordchuck.com
##

{
  :'fr' =>

{
  :number => {
    :format => {
      :separator => ",",
      :precision => 3,
      :delimiter => " "
    },
    :human => {
      :format => {
        :precision => 2,
        :delimiter => ""
      },
      :storage_units => {
        :format => "%n %u",
        :units => {
          :kb => "ko",
          :tb => "To",
          :gb => "Go",
          :byte => {
            :one => "octets",
            :value => "octet"
          },
          :mb => "Mo"
        }
      }
    },
    :currency => {
      :format => {
        :format => "%n %u",
        :unit => "â‚¬",
        :precision => 2
      }
    }
  },
  :activerecord => {
    :errors => {
      :messages => {
        :record_invalid => "La validation a Ã©chouÃ© : {{errors}}",
        :greater_than_or_equal_to => "doit Ãªtre supÃ©rieur ou Ã©gal Ã  {{count}}",
        :less_than_or_equal_to => "doit Ãªtre infÃ©rieur ou Ã©gal Ã  {{count}}",
        :confirmation => "ne concorde pas avec la confirmation",
        :blank => "doit Ãªtre rempli(e)",
        :invalid => "n'est pas valide",
        :exclusion => "n'est pas disponible",
        :odd => "doit Ãªtre impair",
        :wrong_length => "ne fait pas la bonne longueur (doit comporter {{count}} caractÃ¨res)",
        :too_short => "est trop court (au moins {{count}} caractÃ¨res)",
        :even => "doit Ãªtre pair",
        :empty => "doit Ãªtre rempli(e)",
        :less_than => "doit Ãªtre infÃ©rieur Ã  {{count}}",
        :equal_to => "doit Ãªtre Ã©gal Ã  {{count}}",
        :too_long => "est trop long (pas plus de {{count}} caractÃ¨res)",
        :taken => "n'est pas disponible",
        :accepted => "doit Ãªtre acceptÃ©(e)",
        :not_a_number => "n'est pas un nombre",
        :inclusion => "n'est pas inclus(e) dans la liste"
      },
      :template => {
        :body => "Veuillez vÃ©rifier les champs suivants :",
        :header => {
          :one => "Impossible d'enregistrer {{model}}: {{count}} er",
          :value => "Impossible d'enregistrer {{model}}: 1 erreur"
        }
      }
    }
  },
  :nav => {
    :blog => "Blog",
    :photos => "Photos",
    :bio => "Bio",
    :cv => "CV",
    :readings => "Lectures"
  },
  :time => {
    :am => "am",
    :formats => {
      :long_ordinal => "%A %d %B %Y %H:%M:%S %Z",
      :default => "%d %B %Y %H:%M",
      :time => "%H:%M",
      :short => "%d %b %H:%M",
      :only_second => "%S",
      :long => "%A %d %B %Y %H:%M:%S %Z"
    },
    :pm => "pm"
  },
  :date => {
    :month_names => ["~", "janvier", "fÃ©vrier", "mars", "avril", "mai", "juin", "juillet", "aoÃ»t", "septembre", "octobre", "novembre", "dÃ©cembre"],
    :abbr_day_names => ["dim", "lun", "mar", "mer", "jeu", "ven", "sam"],
    :formats => {
      :only_day => "%e",
      :long_ordinal => "%e %B %Y",
      :default => "%d/%m/%Y",
      :short => "%e %b",
      :long => "%e %B %Y"
    },
    :day_names => ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    :abbr_month_names => ["day", "month", "year"]
  },
  :support => {
    :array => {
      :words_connector => ", ",
      :last_word_connector => " et ",
      :two_words_connector => " et ",
      :skip_last_comma => true,
      :sentence_connector => "et"
    }
  },
  :bio_page => {
    :paragraph_1 => "Andy Brett est né le 26 dans un lieu tenu secret dans le nord de l'Ohio Septembre. Formé d'abord par ses parents, puis par des religieuses, et enfin par la méthode socratique, il a quitté l'Ohio à l'âge de 17 ans avec une tendance à poser des questions impertinentes, ainsi que \"le monde réel\" expérience en tant que <a href=\"http://www.kirtlandcc.org/\">cadet</a> , le tuteur, paysagiste conseiller de camp, et le fabricant de sandwich Panera. Heureusement, il n'a pas été dirigé pour le monde réel, mais plutôt la bulle orange de l'université de Princeton.",
    :paragraph_2 => "Après quatre ans, Andy a émergé avec un diplôme et quelques chapeaux plus, y compris Long Trail patrouilleur, chasseur de tempêtes, et l'homme analyste risque pour la santé. Il a également pris de nombreux cours, et tandis que son degré est techniquement en génie civil et environnemental et en sciences informatiques, la majeure partie du crédit pour son enseignement supérieur appartient aux professeurs de ces quatre cours:"
  },
  :datetime => {
    :prompts => {
      :minute => "Minute",
      :second => "Seconde",
      :month => "Mois",
      :hour => "Heure",
      :day => "Jour",
      :year => "AnnÃ©e"
    },
    :distance_in_words => {
      :less_than_x_minutes => {
        :one => "moins de {{count}} minutes",
        :value => "moins de 1 minute",
        :zero => "moins d'une minute"
      },
      :x_days => {
        :one => "{{count}} jours",
        :value => "1 jour"
      },
      :x_seconds => {
        :one => "{{count}} secondes",
        :value => "1 seconde"
      },
      :x_months => {
        :one => "{{count}} mois",
        :value => "1 mois"
      },
      :x_minutes => {
        :one => "{{count}} minutes",
        :value => "1 minute"
      },
      :less_than_x_seconds => {
        :one => "moins de {{count}} secondes",
        :value => "moins de 1 seconde",
        :zero => "moins d'une seconde"
      },
      :about_x_hours => {
        :one => "environ {{count}} heures",
        :value => "environ une heure"
      },
      :about_x_years => {
        :one => "environ {{count}} ans",
        :value => "environ un an"
      },
      :about_x_months => {
        :one => "environ {{count}} mois",
        :value => "environ un mois"
      },
      :over_x_years => {
        :one => "plus de {{count}} ans",
        :value => "plus d'un an"
      },
      :half_a_minute => "une demi-minute"
    }
  }
}

}

